import fs from 'fs';
import path from 'path';
import fg from 'fast-glob';
import { parseFile } from './ast-parser.js';

export async function scanProject(targetDir) {
    const packageJsonPath = path.join(targetDir, 'package.json');
    if (!fs.existsSync(packageJsonPath)) {
        throw new Error('No package.json found in the target directory.');
    }

    const pkgJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
    const dependencies = Object.keys(pkgJson.dependencies || {});

    const files = await fg(['**/*.{js,jsx,ts,tsx}'], {
        cwd: targetDir,
        ignore: ['node_modules/**', 'dist/**', 'build/**']
    });

    const usedDeps = new Set();
    const fileToDeps = {};

    for (const file of files) {
        const filePath = path.join(targetDir, file);
        const fileImports = parseFile(filePath);

        fileToDeps[file] = [];

        fileImports.forEach(imp => {
            const basePackage = imp.startsWith('@')
                ? imp.split('/').slice(0, 2).join('/')
                : imp.split('/')[0];

            usedDeps.add(basePackage);

            if (dependencies.includes(basePackage) && !fileToDeps[file].includes(basePackage)) {
                fileToDeps[file].push(basePackage);
            }
        });
    }

    const unusedDeps = dependencies.filter(dep => !usedDeps.has(dep));

    return {
        scannedFiles: files.length,
        declaredCount: dependencies.length,
        usedCount: dependencies.length - unusedDeps.length,
        unusedDeps,
        usedDeps: Array.from(usedDeps).filter(dep => dependencies.includes(dep)),
        fileToDeps
    };
}

export async function generateArchitectureMap(targetDir, results) {
    const files = results.fileToDeps || {};
    const usedDeps = results.usedDeps || [];
    const unusedDeps = results.unusedDeps || [];

    let mermaidCode = 'graph LR\n';
    const safeId = (str, prefix) => prefix + str.replace(/[^a-zA-Z0-9]/g, '_');

    // Group files by their parent folder to prevent visual clutter
    const folderToDeps = {};
    for (const [file, deps] of Object.entries(files)) {
        if (deps.length > 0) {
            const dir = path.dirname(file);
            const displayFolder = dir === '.' ? 'root' : dir;

            if (!folderToDeps[displayFolder]) {
                folderToDeps[displayFolder] = new Set();
            }
            deps.forEach(dep => folderToDeps[displayFolder].add(dep));
        }
    }

    // 1. Draw connections from Folders to Dependencies
    for (const [folder, deps] of Object.entries(folderToDeps)) {
        const folderId = safeId(folder, 'dir_');
        deps.forEach(dep => {
            const depId = safeId(dep, 'pkg_');
            mermaidCode += `    ${folderId}["[DIR] ${folder}"] --> ${depId}["${dep}"]\n`;
        });
    }

    // 2. Add Unused Dependencies
    unusedDeps.forEach(dep => {
        const depId = safeId(dep, 'pkg_');
        mermaidCode += `    ${depId}["${dep} (UNUSED)"]\n`;
    });

    // 3. Apply Colors and Styles
    mermaidCode += '\n    %% Styling\n';
    mermaidCode += '    classDef unused fill:#fee2e2,stroke:#ef4444,stroke-width:2px,color:#991b1b;\n';
    mermaidCode += '    classDef used fill:#d1fae5,stroke:#10b981,stroke-width:2px,color:#065f46;\n';
    mermaidCode += '    classDef folder fill:#e0e7ff,stroke:#6366f1,stroke-width:1px,color:#3730a3;\n\n';

    usedDeps.forEach(dep => {
        mermaidCode += `    class ${safeId(dep, 'pkg_')} used;\n`;
    });

    unusedDeps.forEach(dep => {
        mermaidCode += `    class ${safeId(dep, 'pkg_')} unused;\n`;
    });

    for (const folder of Object.keys(folderToDeps)) {
        mermaidCode += `    class ${safeId(folder, 'dir_')} folder;\n`;
    }

    const markdown = `# Architecture & Dependency Map\n\n> Auto-generated by \`depmapx\`\n\n\`\`\`mermaid\n${mermaidCode}\n\`\`\`\n`;

    const outputPath = path.join(targetDir, 'ARCHITECTURE.md');
    fs.writeFileSync(outputPath, markdown);

    return outputPath;
}